CREATE TABLE [dbo].[PRODUTO] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [NOME]      VARCHAR (50)  NOT NULL,
    [DESCRICAO] VARCHAR (150) NOT NULL,
    [PRECO]     VARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[USUARIO] (
    [USUARIO] VARCHAR (20) NOT NULL,
    [SENHA]   VARCHAR (30) NOT NULL
);
INSERT INTO [dbo].[USUARIO] (USUARIO, SENHA)
VALUES ('Caio', 1234);

INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Asssada', '500,00');
INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Frita', '100,00');
INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Escondida', '200,00');
INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Cozida', '900,00');
INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Crua', '750,00');
INSERT INTO [dbo].[PRODUTO] (NOME, DESCRICAO, PRECO)
VALUES ('Batata', 'Refogada', '50,00');
