CREATE TABLE [dbo].[PRODUTO] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [NOME]      VARCHAR (50)  NOT NULL,
    [DESCRICAO] VARCHAR (150) NOT NULL,
    [PRECO]     VARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[USUARIO] (
    [USUARIO] VARCHAR (20) NOT NULL,
    [SENHA]   VARCHAR (30) NOT NULL
);